/** Maps a user's saved profile to the correct quiz testId and mock exam baseTestId. */

export function getDefaultTestId(
  targetState: string | null,
  targetLicense: string | null,
): string {
  const state   = (targetState   ?? 'CA').toUpperCase();
  const license = (targetLicense ?? 'permit').toLowerCase();

  const key = `${state}-${license}`;
  const MAP: Record<string, string> = {
    'CA-permit':      'california-permit',
    'CA-motorcycle':  'california-motorcycle',
    'CA-cdl_general': 'california-cdl-general',
    'TX-permit':      'texas-permit',
    'TX-motorcycle':  'texas-motorcycle',
    'TX-cdl_general': 'texas-cdl-general',
    'FL-permit':      'florida-permit',
    'FL-motorcycle':  'florida-motorcycle',
    'FL-cdl_general': 'florida-cdl-general',
    'NY-permit':      'new-york-permit',
    'NY-motorcycle':  'new-york-motorcycle',
    'NY-cdl_general': 'new-york-cdl-general',
    'GA-permit':      'georgia-permit',
    'GA-motorcycle':  'georgia-motorcycle',
    'GA-cdl_general': 'georgia-cdl-general',
    'OH-permit':      'ohio-permit',
    'OH-motorcycle':  'ohio-motorcycle',
    'OH-cdl_general': 'ohio-cdl-general',
    'PA-permit':      'pennsylvania-permit',
    'PA-motorcycle':  'pennsylvania-motorcycle',
    'PA-cdl_general': 'pennsylvania-cdl-general',
    'IL-permit':      'illinois-permit',
    'IL-motorcycle':  'illinois-motorcycle',
    'IL-cdl_general': 'illinois-cdl-general',
    'NC-permit':      'north-carolina-permit',
    'NC-motorcycle':  'north-carolina-motorcycle',
    'NC-cdl_general': 'north-carolina-cdl-general',
    'AZ-permit':      'arizona-permit',
    'AZ-motorcycle':  'arizona-motorcycle',
    'AZ-cdl_general': 'arizona-cdl-general',
    'MI-permit':      'michigan-permit',
    'MI-cdl_general': 'michigan-cdl-general',
    'MO-permit':      'missouri-permit',
    'MO-motorcycle':  'missouri-motorcycle',
    'MO-cdl_general': 'missouri-cdl-general',
    'TN-permit':      'tennessee-permit',
    'TN-cdl_general': 'tennessee-cdl-general',
    'VA-permit':      'virginia-permit',
    'VA-motorcycle':  'virginia-motorcycle',
    'VA-cdl_general': 'virginia-cdl-general',
    'WA-permit':      'washington-permit',
    'WA-cdl_general': 'washington-cdl-general',
    'NJ-permit':      'new-jersey-permit',
    'NJ-cdl_general': 'new-jersey-cdl-general',
    'MD-permit':      'maryland-permit',
    'MD-motorcycle':  'maryland-motorcycle',
    'MD-cdl_general': 'maryland-cdl-general',
    'MA-permit':      'massachusetts-permit',
    'MA-motorcycle':  'massachusetts-motorcycle',
    'MA-cdl_general': 'massachusetts-cdl-general',
    'WI-permit':      'wisconsin-permit',
    'WI-cdl_general': 'wisconsin-cdl-general',
    'OR-permit':      'oregon-permit',
    'OR-motorcycle':  'oregon-motorcycle',
    'OR-cdl_general': 'oregon-cdl-general',
    'OK-permit':      'oklahoma-permit',
    'OK-cdl_general': 'oklahoma-cdl-general',
    'CT-permit':      'connecticut-permit',
    'CT-cdl_general': 'connecticut-cdl-general',
    'NV-permit':      'nevada-permit',
    'NV-cdl_general': 'nevada-cdl-general',
    'UT-permit':      'utah-permit',
    'UT-cdl_general': 'utah-cdl-general',
    // ── Queued states (not yet live) ──────────────────────────────────────────
    'SC-permit':      'south-carolina-permit',
    'SC-motorcycle':  'south-carolina-motorcycle',
    'SC-cdl_general': 'south-carolina-cdl-general',
    'IN-permit':      'indiana-permit',
    'IN-motorcycle':  'indiana-motorcycle',
    'IN-cdl_general': 'indiana-cdl-general',
    'AL-permit':      'alabama-permit',
    'AL-motorcycle':  'alabama-motorcycle',
    'AL-cdl_general': 'alabama-cdl-general',
    'CO-permit':      'colorado-permit',
    'CO-motorcycle':  'colorado-motorcycle',
    'CO-cdl_general': 'colorado-cdl-general',
    'IA-permit':      'iowa-permit',
    'IA-motorcycle':  'iowa-motorcycle',
    'IA-cdl_general': 'iowa-cdl-general',
    'KY-permit':      'kentucky-permit',
    'KY-motorcycle':  'kentucky-motorcycle',
    'KY-cdl_general': 'kentucky-cdl-general',
    'LA-permit':      'louisiana-permit',
    'LA-motorcycle':  'louisiana-motorcycle',
    'LA-cdl_general': 'louisiana-cdl-general',
    'MN-permit':      'minnesota-permit',
    'MN-motorcycle':  'minnesota-motorcycle',
    'MN-cdl_general': 'minnesota-cdl-general',
    'AR-permit':      'arkansas-permit',
    'AR-motorcycle':  'arkansas-motorcycle',
    'AR-cdl_general': 'arkansas-cdl-general',
    'MS-permit':      'mississippi-permit',
    'MS-motorcycle':  'mississippi-motorcycle',
    'MS-cdl_general': 'mississippi-cdl-general',
    'KS-permit':      'kansas-permit',
    'KS-motorcycle':  'kansas-motorcycle',
    'KS-cdl_general': 'kansas-cdl-general',
    'NM-permit':      'new-mexico-permit',
    'NM-motorcycle':  'new-mexico-motorcycle',
    'NM-cdl_general': 'new-mexico-cdl-general',
    'NE-permit':      'nebraska-permit',
    'NE-motorcycle':  'nebraska-motorcycle',
    'NE-cdl_general': 'nebraska-cdl-general',
    'ID-permit':      'idaho-permit',
    'ID-motorcycle':  'idaho-motorcycle',
    'ID-cdl_general': 'idaho-cdl-general',
    'WV-permit':      'west-virginia-permit',
    'WV-motorcycle':  'west-virginia-motorcycle',
    'WV-cdl_general': 'west-virginia-cdl-general',
    'HI-permit':      'hawaii-permit',
    'HI-motorcycle':  'hawaii-motorcycle',
    'HI-cdl_general': 'hawaii-cdl-general',
    'NH-permit':      'new-hampshire-permit',
    'NH-motorcycle':  'new-hampshire-motorcycle',
    'NH-cdl_general': 'new-hampshire-cdl-general',
    'ME-permit':      'maine-permit',
    'ME-motorcycle':  'maine-motorcycle',
    'ME-cdl_general': 'maine-cdl-general',
    'MT-permit':      'montana-permit',
    'MT-motorcycle':  'montana-motorcycle',
    'MT-cdl_general': 'montana-cdl-general',
    'RI-permit':      'rhode-island-permit',
    'RI-motorcycle':  'rhode-island-motorcycle',
    'RI-cdl_general': 'rhode-island-cdl-general',
    'DE-permit':      'delaware-permit',
    'DE-motorcycle':  'delaware-motorcycle',
    'DE-cdl_general': 'delaware-cdl-general',
    'SD-permit':      'south-dakota-permit',
    'SD-motorcycle':  'south-dakota-motorcycle',
    'SD-cdl_general': 'south-dakota-cdl-general',
    'ND-permit':      'north-dakota-permit',
    'ND-motorcycle':  'north-dakota-motorcycle',
    'ND-cdl_general': 'north-dakota-cdl-general',
    'AK-permit':      'alaska-permit',
    'AK-motorcycle':  'alaska-motorcycle',
    'AK-cdl_general': 'alaska-cdl-general',
    'VT-permit':      'vermont-permit',
    'VT-motorcycle':  'vermont-motorcycle',
    'VT-cdl_general': 'vermont-cdl-general',
    'WY-permit':      'wyoming-permit',
    'WY-motorcycle':  'wyoming-motorcycle',
    'WY-cdl_general': 'wyoming-cdl-general',
  };
  return MAP[key] ?? 'california-permit';
}

/** Returns true when the license type has no mock exams. */
export function hasMockExams(targetLicense: string | null): boolean {
  const license = (targetLicense ?? 'permit').toLowerCase();
  return license === 'permit';
}
