import type { MetadataRoute } from "next";

const BASE = "https://caredmvprep.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const high: string[] = [
    "",
    "/states",
    "/california-dmv-practice-test",
    "/texas-dmv-practice-test",
    "/florida-dmv-practice-test",
    "/new-york-dmv-practice-test",
    "/illinois-dmv-practice-test",
    "/pennsylvania-dmv-practice-test",
    "/ohio-dmv-practice-test",
    "/georgia-dmv-practice-test",
    "/north-carolina-dmv-practice-test",
    "/michigan-dmv-practice-test",
    "/virginia-dmv-practice-test",
    "/washington-dmv-practice-test",
    "/arizona-dmv-practice-test",
    "/new-jersey-dmv-practice-test",
    "/massachusetts-dmv-practice-test",
    "/maryland-dmv-practice-test",
    "/tennessee-dmv-practice-test",
    "/colorado-dmv-practice-test",
    "/minnesota-dmv-practice-test",
    "/indiana-dmv-practice-test",
    "/missouri-dmv-practice-test",
    "/wisconsin-dmv-practice-test",
    "/alabama-dmv-practice-test",
    "/south-carolina-dmv-practice-test",
    "/louisiana-dmv-practice-test",
    "/kentucky-dmv-practice-test",
    "/oregon-dmv-practice-test",
    "/oklahoma-dmv-practice-test",
    "/connecticut-dmv-practice-test",
    "/alaska-dmv-practice-test",
    "/arkansas-dmv-practice-test",
    "/delaware-dmv-practice-test",
    "/hawaii-dmv-practice-test",
    "/idaho-dmv-practice-test",
    "/iowa-dmv-practice-test",
    "/kansas-dmv-practice-test",
    "/maine-dmv-practice-test",
    "/mississippi-dmv-practice-test",
    "/montana-dmv-practice-test",
    "/nebraska-dmv-practice-test",
    "/nevada-dmv-practice-test",
    "/new-hampshire-dmv-practice-test",
    "/new-mexico-dmv-practice-test",
    "/north-dakota-dmv-practice-test",
    "/rhode-island-dmv-practice-test",
    "/south-dakota-dmv-practice-test",
    "/utah-dmv-practice-test",
    "/vermont-dmv-practice-test",
    "/west-virginia-dmv-practice-test",
    "/wyoming-dmv-practice-test",
    "/cdl-practice-test",
    "/motorcycle-practice-test",
    "/pricing",
  ];

  const stateLicense: string[] = [
    "/california-motorcycle-practice-test",
    "/california-cdl-practice-test",
    "/texas-motorcycle-practice-test",
    "/texas-cdl-practice-test",
    "/florida-motorcycle-practice-test",
    "/florida-cdl-practice-test",
    "/new-york-motorcycle-practice-test",
    "/new-york-cdl-practice-test",
    "/illinois-motorcycle-practice-test",
    "/illinois-cdl-practice-test",
    "/pennsylvania-motorcycle-practice-test",
    "/pennsylvania-cdl-practice-test",
    "/ohio-motorcycle-practice-test",
    "/ohio-cdl-practice-test",
    "/georgia-motorcycle-practice-test",
    "/georgia-cdl-practice-test",
    "/north-carolina-motorcycle-practice-test",
    "/north-carolina-cdl-practice-test",
    "/michigan-motorcycle-practice-test",
    "/michigan-cdl-practice-test",
    "/virginia-motorcycle-practice-test",
    "/virginia-cdl-practice-test",
    "/washington-motorcycle-practice-test",
    "/washington-cdl-practice-test",
    "/arizona-motorcycle-practice-test",
    "/arizona-cdl-practice-test",
    "/new-jersey-motorcycle-practice-test",
    "/new-jersey-cdl-practice-test",
    "/massachusetts-motorcycle-practice-test",
    "/massachusetts-cdl-practice-test",
    "/maryland-motorcycle-practice-test",
    "/maryland-cdl-practice-test",
    "/tennessee-motorcycle-practice-test",
    "/tennessee-cdl-practice-test",
    "/colorado-motorcycle-practice-test",
    "/colorado-cdl-practice-test",
    "/minnesota-motorcycle-practice-test",
    "/minnesota-cdl-practice-test",
    "/indiana-motorcycle-practice-test",
    "/indiana-cdl-practice-test",
    "/missouri-motorcycle-practice-test",
    "/missouri-cdl-practice-test",
    "/wisconsin-motorcycle-practice-test",
    "/wisconsin-cdl-practice-test",
    "/alabama-motorcycle-practice-test",
    "/alabama-cdl-practice-test",
    "/south-carolina-motorcycle-practice-test",
    "/south-carolina-cdl-practice-test",
    "/louisiana-motorcycle-practice-test",
    "/louisiana-cdl-practice-test",
    "/kentucky-motorcycle-practice-test",
    "/kentucky-cdl-practice-test",
    "/oregon-motorcycle-practice-test",
    "/oregon-cdl-practice-test",
    "/oklahoma-motorcycle-practice-test",
    "/oklahoma-cdl-practice-test",
    "/connecticut-motorcycle-practice-test",
    "/connecticut-cdl-practice-test",
    "/alaska-motorcycle-practice-test",
    "/alaska-cdl-practice-test",
    "/arkansas-motorcycle-practice-test",
    "/arkansas-cdl-practice-test",
    "/delaware-motorcycle-practice-test",
    "/delaware-cdl-practice-test",
    "/hawaii-motorcycle-practice-test",
    "/hawaii-cdl-practice-test",
    "/idaho-motorcycle-practice-test",
    "/idaho-cdl-practice-test",
    "/iowa-motorcycle-practice-test",
    "/iowa-cdl-practice-test",
    "/kansas-motorcycle-practice-test",
    "/kansas-cdl-practice-test",
    "/maine-motorcycle-practice-test",
    "/maine-cdl-practice-test",
    "/mississippi-motorcycle-practice-test",
    "/mississippi-cdl-practice-test",
    "/montana-motorcycle-practice-test",
    "/montana-cdl-practice-test",
    "/nebraska-motorcycle-practice-test",
    "/nebraska-cdl-practice-test",
    "/nevada-motorcycle-practice-test",
    "/nevada-cdl-practice-test",
    "/new-hampshire-motorcycle-practice-test",
    "/new-hampshire-cdl-practice-test",
    "/new-mexico-motorcycle-practice-test",
    "/new-mexico-cdl-practice-test",
    "/north-dakota-motorcycle-practice-test",
    "/north-dakota-cdl-practice-test",
    "/rhode-island-motorcycle-practice-test",
    "/rhode-island-cdl-practice-test",
    "/south-dakota-motorcycle-practice-test",
    "/south-dakota-cdl-practice-test",
    "/utah-motorcycle-practice-test",
    "/utah-cdl-practice-test",
    "/vermont-motorcycle-practice-test",
    "/vermont-cdl-practice-test",
    "/west-virginia-motorcycle-practice-test",
    "/west-virginia-cdl-practice-test",
    "/wyoming-motorcycle-practice-test",
    "/wyoming-cdl-practice-test",
  ];

  const cdl: string[] = [
    "/cdl-general-knowledge",
    "/cdl-air-brakes",
    "/cdl-hazmat",
    "/cdl-passenger",
    "/cdl-school-bus",
    "/cdl-tanker",
    "/cdl-doubles-triples",
    "/cdl-combination-vehicles",
  ];

  const moto: string[] = [
    "/motorcycle-permit-test",
    "/motorcycle-endorsement-test",
    "/motorcycle-license-test",
    "/motorcycle-road-signs",
    "/motorcycle-safety-tips",
  ];

  const resources: string[] = [
    "/resources",
    "/dmv-study-tips",
    "/drivers-license-guide",
    "/cdl-guide",
    "/motorcycle-guide",
    "/faqs",
    "/about",
    "/contact",
    "/terms",
    "/privacy",
  ];

  const toEntry = (route: string, priority: number, freq: MetadataRoute.Sitemap[number]["changeFrequency"]) => ({
    url: `${BASE}${route}`,
    lastModified: now,
    changeFrequency: freq,
    priority,
  });

  return [
    ...high.map((r) => toEntry(r, r === "" ? 1.0 : 0.9, r === "" ? "weekly" : "monthly")),
    ...stateLicense.map((r) => toEntry(r, 0.8, "monthly")),
    ...cdl.map((r) => toEntry(r, 0.8, "monthly")),
    ...moto.map((r) => toEntry(r, 0.8, "monthly")),
    ...resources.map((r) => toEntry(r, 0.7, "monthly")),
  ];
}
